spring:
    datasource:
        url: jdbc:mysql://localhost:3306/rms
        username: root
        password: password
    jpa:
    # Hibernate ddl auto (none, create, create-drop, update, validate)
        hibernate:
            ddl-auto: create-drop
        show-sql: true

server:
    port: 8000

security:
    user:
        name: aziz@mitrais.com
        password: password
    oauth2:
        client:
            client-id: client
            client-secret: secret
        token-timeout: 3600